### ISSUE TITLE
Is this LRPE-d?

### ISSUE THREAD

**Issue by catid** [Doraemonzzz/nanoTransNormer#1]
Asking about this part of the code:

https://github.com/Doraemonzzz/nanoTransNormer/blob/d9e635a8c8243c409942b0ab9758176869468d4f/transnormer/model.py#L56

This looks very simple compared to even the LRPE Python code provided with the paper: https://arxiv.org/pdf/2307.09270.pdf

Is it correct, or is it not the same algorithm used in TransnormerLLM?

**Comment by Doraemonzzz** [comment]
Hello, this is the implementation of Unitary (Solution 1) in the Lrpe paper, due to the fact that we ultimately used the real part of complex numbers:

$$
\begin{aligned}

x&=r_x(\cos(\theta_x)+i\sin(\theta_y))  \\
y&=r_y(\cos(\theta_y)+i\sin(\theta_y))   \\
\mathrm{Re}(x^{\mathbf {H}}y)&=\mathrm{Re}[(r_x(\cos(\theta_x)-i\sin(\theta_y)))(r_y(\cos(\theta_y)+i\sin(\theta_y))] \\
&=r_xr_y
[\cos(\theta_x)\cos(\theta_y)+\sin(\theta_x)\sin(\theta_y)]

\end{aligned}
$$
On the other hand, the decay part in Lrpe-d is implemented at:

https://github.com/Doraemonzzz/nanoTransNormer/blob/d9e635a8c8243c409942b0ab9758176869468d4f/transnormer/model.py#L173

**Comment by Doraemonzzz** [comment]
It seems there is an issue with the display of the mathematical formula, here is a screenshot of the formula:
<img width="483" alt="image" src="https://github.com/Doraemonzzz/nanoTransNormer/assets/35402766/d656b7bc-fb59-4c50-98da-e728c4341a1b">

**Comment by Doraemonzzz** [comment]
As an addition, the code here uses lightning1, and I will be updating to lightning2 soon.
